apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: ApplicationSet
    path: patch.yaml
   - target:
      kind: ApplicationSet
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: podinfo2-prod-01
    