apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: ApplicationSet
    path: patch.yaml
  - target:
      kind: ApplicationSet
      name: demo02-podinfo
    patch: |-
      - op: replace
        path: /metadata/name
        value: demo02-podinfo-dev
  - target:
      kind: ApplicationSet
      name: demo02-httpbin
    patch: |-
      - op: replace
        path: /metadata/name
        value: demo02-httpbin-dev
    