apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ignored-but-required
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev-001
        ring: '0'
        environment: dev
        url: https://kubernetes.default.svc
      - cluster: engineering-dev-002
        ring: '0'
        environment: dev
        url: https://kubernetes.default.svc