apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ignored-but-required
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-stage-001
        ring: '0'
        environment: stage
        url: https://kubernetes.default.svc